title: Traffic Tamer
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - AboutUs.md
  -ProjectDescription.md

minima:
  skin: solarized
